global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'macos_host'
    static_configs:
      - targets: ['host.docker.internal:9100']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['mysqld_exporter:9104']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']